### PR TITLE
Fix for #99

### PR DESCRIPTION
**Pull request by allegroLeiden**
Fix the line blending (#99)

### CODE REVIEW

**Comment by ParfenovS** [comment]
nextLineWithBlend will be incremented on each cycle of matrix inversion loop (stateq.c file) which begins with:
while((diff>TOL && iter<MAXITER) || iter<5){
getjbar(id,m,g,ispec,par,blends,nextLineWithBlend,mp,halfFirstDs);

it is strange. Should one replace this by:

while((diff>TOL && iter<MAXITER) || iter<5){
*nextLineWithBlend = 0;
getjbar(id,m,g,ispec,par,blends,nextLineWithBlend,mp,halfFirstDs);

**Comment by ParfenovS** [comment]
Or maybe one should use some auxiliary variable. For example

while((diff>TOL && iter<MAXITER) || iter<5){
int nextLineWithBlend1 = *nextLineWithBlend;
getjbar(id,m,g,ispec,par,blends,&nextLineWithBlend1,mp,halfFirstDs);

and after the end of matrix inversion loop in stateq one can add the following line:

*nextLineWithBlend = nextLineWithBlend1;

**Comment by tlunttil** [comment]
I agree with @ParfenovS , the second version with the auxiliary variable should work. Setting *nextLineWithBlend to zero would probably be ok unless there are several species.

**Comment by ParfenovS** [comment]
I think that there is also an error in raytracing.
If the user specifies img.trans then the code assumes that this transition belongs to the first species and 
`img[im].freq=m[0].freq[img[im].trans];`  (see raytrace procedure)

This PR contains following code in the traceray procedure:

`if(img[im].trans > -1){
                    lineRedShift=(m[molI].freq[img[im].trans]-m[molI].freq[lineI])/m[molI].freq[img[im].trans]*CLIGHT;`

where molI changes in the loop. This part should be replaced by 

`if(img[im].trans > -1){
                    lineRedShift=(m[0].freq[img[im].trans]-m[molI].freq[lineI])/m[0].freq[img[im].trans]*CLIGHT;`

**Comment by ParfenovS** [comment]
I just noticed that the master branch also contains this error.

**Comment by ParfenovS** [comment]
Actually, whole this part:
`if(img[im].trans > -1){
  shift=(m[0].freq[img[im].trans]-m[molI].freq[lineI])/m[0].freq[img[im].trans]*CLIGHT;
} else {
  shift=(img[im].freq-m[molI].freq[lineI])/img[im].freq*CLIGHT;
}`

can be safely replaced by a single line:
`shift=(img[im].freq-m[molI].freq[lineI])/img[im].freq*CLIGHT;`

**Comment by tlunttil** [comment]
Right, there's no need for `if(img[im].trans > -1)` part, because `img[im].freq` is set in `raytrace()` (line 220 in master branch).

This bug, too, only seems to have an effect if there are multiple species. I'm not surprised if there are some further bugs with multi-species calculations, those parts have probably not been used/tested much.

**Comment by allegroLeiden** [comment]
Thanks for pointing this out @ParfenovS. Damn - I thought this `nextLineWithBlend` thing was rather a clever idea, but it does depend on the `molI` and `lineI` loops always being nested with no other layers of loop in between, which as you point out is alas not the case in the sequence of calls which ends in `getjbar()`.

**Comment by allegroLeiden** [comment]
I have fixed the `getjbar()` problem now. I decided to do this via a redesign of the `blendInfo` struct. Pseudocode for the whole call nesting from within 'levelPops()' to `getjbar()` is as follows:

    nextMolWithBlend = 0;
    for(ispec=0;ispec<par->nSpecies;ispec++){
      stateq(ispec, nextMolWithBlend, etc){
        while((diff>TOL && iter<MAXITER) || iter<5){
          getjbar(ispec, nextMolWithBlend, etc){
            for(iphot=0;iphot<g[posn].nphot;iphot++){
              if(mp[molI].vfac[iphot]>0){

                nextLineWithBlend = 0;
                for(lineI=0;lineI<m[molI].nline;lineI++){
                  // blah
                  if(par->blend && molI==blends.mols[nextMolWithBlend].molI\
                  && lineI==blends.mols[nextMolWithBlend].lines[nextLineWithBlend].lineI){
                    // do blend stuff

                    nextLineWithBlend++;
                    if(nextLineWithBlend>=blends.mols[nextMolWithBlend].numLinesWithBlends)
                      nextLineWithBlend = 0; // A dummy value. If we get here, there are no more blends, but we don't want the matrix calls which will blindly check that to read memory out of range. Could have done this cleverer but this works.
                  } // end if mol.line has blends
                } // end loop lineI

              } // end if
            } // end loop iphot
          } // end getjbar()
        } // end while
      } // end stateq()

      if(this molecule had some lines with blends)
        nextMolWithBlend++;
    } // end loop ispec

**Comment by allegroLeiden** [comment]
I'll look at the img.trans thing now, but honestly, sometimes I despair at the task of (i) detecting such problems and (ii) acceptably patching them in ways which don't add more ugliness. This whole style of guess-my-mode-from-some-possibly-irrelevant-values really needs to be replaced by a proper set of booleans. Separating the user params from internal configuration information via PR #77 would be a good launching pad for this, but SM hasn't yet accepted it...

**Comment by ParfenovS** [comment]
The new version of this PR causes segmentation fault in the case of blended lines absence.
The lineBlend procedure frees blends structure if there are no blending lines. In the result, for example, the following statement (photon.c file in this PR) will rise segmentation fault:
`if(par->blend && molI==blends.mols[nextMolWithBlend].molI\
          && lineI==blends.mols[nextMolWithBlend].lines[nextLineWithBlend].lineI){`
because it tries to access deallocated blends.mols array.

Possible fix may look like:
`if(par->blend && blends.mols!=NULL){`
          `if(molI==blends.mols[nextMolWithBlend].molI\
          && lineI==blends.mols[nextMolWithBlend].lines[nextLineWithBlend].lineI){`

**Comment by tlunttil** [comment]
It can be done within a single if because C short-circuits evaluation of &&:
`if((par->blend) && (par->blends.mols) && (molI==blends.mols[nextMolWithBlend].mol)I\ && (lineI==blends.mols[nextMolWithBlend].lines[nextLineWithBlend].lineI)) {`

You also need to make sure that `par->blend.mols` gets set to NULL after freeing, it doesn't seem to be done at least in 'freeBlends'.

**Comment by allegroLeiden** [comment]
Thanks guys!

**Comment by allegroLeiden** [comment]
Tuomas I guess your 'par->blends.mols' is a typo. I set blends.mols to NULL after freeing it within lineBlend() but not after the free at the end of levelPops. I guess it might be more conservative practice to set things to NULL inside the various free*() functions, but the pattern in Lime is not to do that, so I think any change should be post-merge, or at least not piecemeal.

**Comment by tlunttil** [comment]
Yes, I meant `blends.mols` inside that `if`. And somehow I failed to see that while you don't set the pointer to NULL inside `freeBlends`, you do it in the next line after calling that...

In general it would probably be cleaner if the various `free*()`s did set pointers to NULL after freeing, but I agree it's more of a nice-to-have at this point, there are more important things to do first.

**Comment by tlunttil** [comment]
There are a couple of strange things (from time immemorial, not new in this PR, but they're sort of related to all this).

-  Line 254 of photon.c (in this PR): why vfac[0] instead of vfac[molI]?
-  In fact, why is the local vfac (that is stored in mp[molI].vfac[iphot]) done the way it is in the first place. Wouldn't it be better if it were strictly local without including the half-step thingy? So it would essentially be just an evaluation of a Gaussian at deltav.

New getNextEdge will probably make some (currently working) runs fail due to 'no backwards edges' check ), but I don't know if that is a problem. Anyway, the fundamental problem #101 is in the sink point placement/usage.

**Comment by allegroLeiden** [comment]
- vfac[0] is probably a typo. These merges are pretty tricky.
- I have no strong opinion but I would guess this belongs with the other fixes to photon propagation which I hope you will pr some time.

**Comment by tlunttil** [comment]
Right, I'll think about the vfac thing and maybe do that together with the other propagation stuff.

My only question is then whether the bailout in case of 'no edges in the forward half-space' is the right way to go? Current version would happily(?) run in such cases, which can easily happen if the number of boundary sink points is lowish. The whole sink issue needs to be dealt with at some point, but a good solution won't be ready for 1.6. I'm wondering if instead of bailout it would be better to only issue a warning and choose the 'least-bad' edge.

**Comment by allegroLeiden** [comment]
> I'm wondering if instead of bailout it would be better to only issue a warning and choose the 'least-bad' edge.

Yeah, ok. This is probably a better idea.

By the way, I changed vfac[0] to vfac[molI] already.

**Comment by allegroLeiden** [comment]
> Right, I'll think about the vfac thing and maybe do that together with the other propagation stuff.

Or by 'vfac thing' do you mean 'why do vfac for the first step in the first place'. I guess you do.

**Comment by tlunttil** [comment]
> Or by 'vfac thing' do you mean 'why do vfac for the first step in the first place'. I guess you do.

Yes ;)  

Re: edge selection, allowing backtracking can of course lead to infinite loops, which is how I first found the problem. But if the user is given a warning, at least getting stuck won't come as a complete surprise...

**Comment by tlunttil** [comment]
I think this one's ready for merging, too. And thanks to @ParfenovS for spotting those problems.

**Comment by allegroLeiden** [comment]
Time to resolve the conflicts @smaret ?

**Comment by smaret** [comment]
@allegroLeiden Yes, please do.

**Pull request merged**
