### PR TITLE
Untangling - starting with the dust/knu thing

### PR DESCRIPTION
**Pull request by allegroLeiden**
There are a lot of changes in this single commit, but TBH I am about out of patience with nibbling away at major LIME issues over a space of months, having to waste time on copious amounts of repetition of the same mods and merges. I don't understand why some of you are worrying about the exactness of the results produced by this software when in my view it is at least 2 stages away from that point. We know there are problems with the algorithm; but the algorithm fixes are waiting on fixes for the code structure - the kind of thing which should have been sorted out before 1st release. First let's get the structure right, so it is not an enormous pain constantly to have to work around all the knots and peculiarities; then fix the algorithm; then by all means let's look at the numbers. The present PR is designed to make a leap towards fixing stage no. 1, i.e. code structure. There is more that could/should be done but hopefully the present PR accomplishes a major chunk of what was needed. The details of the changes are in the commit.

This addresses issue #151 BTW.

### CODE REVIEW

**Comment by tlunttil** [comment]
This seems to have some overlap/conflicts with my PR that I submitted 15 minutes later...

**Comment by allegroLeiden** [comment]
Um, yeah - do you have a cunning plan?

**Comment by tlunttil** [comment]
It's probably easier to merge your PR and then redo mine on top of that. My PR doesn't have any structural changes apart from those related to the new lineshape/velocity integration stuff (and maybe we'll keep also the old scheme).

**Comment by allegroLeiden** [comment]
I am going to force push in a minute to try to fix the wrapping of the commit message. Note to self: stop using %$#&^ pico as editor!

**Comment by tlunttil** [comment]
Should I in turn have a look at this? We'll also need to think about how we'll eventually merge this and #153 (for example, should we also keep the old velocity integration option in the code).

**Comment by allegroLeiden** [comment]
> Should I in turn have a look at this?

Yes please.

**Comment by tlunttil** [comment]
I noticed that you read/write dummy variables to keep binary population files compatible with previous versions now that norm/norminv are no longer used. Is compatibility that important? I'm just thinking that if we don't drop the unnecessary fields from binary population files now, we'll probably never will...

**Comment by allegroLeiden** [comment]
I had in mind to break backward-compatibility at release 2.0 (some time in the misty future). Hopefully at that point we would be able to throw away all the horrible CSV I/O altogether.

**Comment by tlunttil** [comment]
This looks fine to me.

**Comment by tlunttil** [comment]
Should we (well, @allegroLeiden) go ahead with the merge? This is big enough change to make a difference in writing many of the following PRs.

**Comment by allegroLeiden** [comment]
I don't have many hours today before I head off to Lisbon but I'll try to bring this up to date with master. If I succeed then I'll merge it without more ado.

**Pull request merged**
