### PR TITLE
Allows easy integration of LIME into ARTIST

### PR DESCRIPTION
**Pull request by rschaaf-aifa**
One central element of ARTIST is a SWIG interface to LIME to allow calling LIME from Python. Since LIME is designed as a stand-alone program, integrating LIME into ARTIST so far requires changes in LIME's code, mainly in aux.c where the input parameters and images are allocated and initialized.

In this PR, the critical parts of `parseInput` and `freeInput` in aux.c are moved to the new functions `initParImg` and `freeParImg` in main.c. In addition, the `main` function is split into the functions `run` and `main` (both in main.c), where `run` can serve as an interface to LIME for external programs (such as ARTIST), and `main` is used for stand-alone LIME.

Besides this structural change, some minor changes are necessary for easy integration of LIME into ARTIST:
- Made `silent` a global variable instead of a global constant
- Added a standard `#ifndef #define` construct to lime.h to avoid problems with including it more than once
- Set locale to "C" explicitely to avoid problems when reading in files
- Removed if statement around `par->nthreads = NTHREADS`

As a result of these changes, LIME's code can remain unchanged when integrating it into ARTIST which will make integration of future LIME versions much easier than in the past.

### CODE REVIEW

**Comment by allegroLeiden** [comment]
Otherwise the PR looks fine.

**Comment by rschaaf-aifa** [comment]
Thank you @allegroLeiden for your comments. 

ad 1) You are right. I removed the now unnecessary check from aux.c.

ad 2) Again you are right what the malloc of `molData` is concerned; I removed the new code as you suggested. I am not sure what exactly you mean with the test of `par->nSpecies`, I could not find these lines in the code.

ad 3) These functions are used only within main.c, and will most probably never be used elsewhere. So there is no need to add them in the (already too long) `lime.h`. However, to make this clearer, I added appropriate forward declarations in `main.c`.

ad 4) OK

ad 5) Fair point. I am using several editors/IDEs on more than one computer, so setting all these tools up properly is a bit of a nuisance. I will try to improve on this point.

**Comment by smaret** [comment]
@rschaaf-aifa Did you close this PR intentionally?

**Comment by rschaaf-aifa** [comment]
Oops, sorry, that was a mistake. I am still not familiar enough with github...

**Comment by allegroLeiden** [comment]
@rschaaf-aifa re the test of `par->nSpecies`: the first example (which began at an `else` statement at line 29 of aux.c in your previous code, and part of the block mallocing the molData object) has now been removed; the second example, namely the line

    if( par->nSpecies == 0 )

was formerly at line 79 of main.c and is now at line 87. As I remarked previously, the `==` here should probably be changed to `<=`, but this is now independent of your PR and were therefore better to be done elsewhere.

**Comment by rschaaf-aifa** [comment]
Although independent of the main purpose of the PR, I followed your suggestion @allegroLeiden and changed the test accordingly.

**Pull request merged**
