### PR TITLE
Faster stateq

### PR DESCRIPTION
**Pull request by tlunttil**
Some rearrangement in stateq.c to make things faster and cleaner. Also removed some old unused code.

### CODE REVIEW

**Comment by tlunttil** [comment]
While I was testing this PR I noticed that with >1 threads results from different runs are not bit-level identical even if -t switch is used. This was not caused by this PR, also master branch has the same issue. I'll have a look tomorrow.

**Comment by tlunttil** [comment]
The problem was dynamic omp scheduling in levelPops(). I removed it and now the results from different runs are identical when -t switch is used. There may be a slight performance penalty, but it's probably not enough to make any difference.

**Comment by allegroLeiden** [comment]
Thanks for this, I'll have a look at it next week.

**Comment by allegroLeiden** [comment]
Sorry I was so long checking this. Our bloody stupid story of disk failures which started last Nov continues unabated, it's been keeping me busy. :(

**Pull request merged**
