### PR TITLE
Fixes the data race in raytracing (#203)

### PR DESCRIPTION
**Pull request by allegroLeiden**
I should make the caveat that the valgrind tool DRD still reports problems; however since these all occur outside the parallel section of raytrace.c, I don't understand what is going on. I attach the log file. Any ideas @tlunttil, or anybody else?

[dlog.txt](https://github.com/lime-rt/lime/files/713608/dlog.txt)

To generate this I did
```
  cd example
  ../lime -n -t -p 4 model_lte.c
  ^c
  valgrind --tool=drd --log-file=dlog.txt lime_<whatever>.x
```

BTW I was not able to squash the 'Minor' commit message via rebasing. Git seems to get confused after a merge.

### CODE REVIEW

**Comment by tlunttil** [comment]
Maybe there are some dangling pointers from earlier parts which then confuse valgrind? Does memcheck complain about anything? On the other hand spurious error messages are not unheard of.

If you run with -DTEST a few times, are the results identical on bit-level? If so, there's probably no error.

BTW, it could be worth looking at parallelising the (unparallelised) regions that drd complained about. At least that interpolation part sometimes takes a non-negligible amount of time. (There's also a cosmetic issue that the progress bar/percentage doesn't take into account time spent there, so it may get stuck at near 1005 for a while.)

**Comment by allegroLeiden** [comment]
> Does memcheck complain about anything?

No.

> If you run with -DTEST a few times, are the results identical on bit-level?

Yes.

> BTW, it could be worth looking at parallelising the (unparallelised) regions that drd complained about.

Maybe later - for now I just want to fix #203 and issue a patch.

**Comment by allegroLeiden** [comment]
> Does memcheck complain about anything?

Oops - I looked too quick. There are zero errors, but there are some leaks. Probably unrelated to the drd problem, but I'll fix them anyway.

**Comment by tlunttil** [comment]
Not related to drd warnings, but something I noticed when I was looking at the code: what is xySquared (starting from line 999 of raytrace.c) used for? Nothing, it seems...

**Comment by allegroLeiden** [comment]
Hmm yeah, seems like fossilized code. I'll nix it.

**Comment by tlunttil** [comment]
If the drd problems still remain, they could maybe be related to some dangling pointers confusing valgrind (it seems generally pointers are not NULLed in LIME after freeing). I might have a look at this later, but in my opinion you could merge this PR.

**Pull request merged**
