### PR TITLE
No-curses option

### PR DESCRIPTION
**Pull request by smaret**
A rebased version of @imckstewart 's PR #51.

### CODE REVIEW

**Comment by smaret** [comment]
@imckstewart : The completion % look incorrect. LIME says that the grid build is 99.9% completed when it starts, and then it takes a while before it is finished:

```
cd example
../lime -n model.c 
*** LIME, The versatile line modeling engine, Ver. 1.5
   Building grid: 99.90 percent done
```

Also the photon propagation completion cycles from 0% to 100% and back several times before completion.

**Comment by smaret** [comment]
Note the `lime -n` to turn off ncurses output.

**Comment by allegroLeiden** [comment]
I'll see if I can fix these things.

**Comment by allegroLeiden** [comment]
Fixes in the latest nocurses upload.

**Pull request merged**
